### PR TITLE
Switch base image to rocker/verse

### LINKED ISSUE #2: Add support for rmarkdown
Switching the base image to rocker/verse https://hub.docker.com/r/rocker/verse

will add rmarkdown support and bring our sandbox and transformation environments more in-line

### PR DESCRIPTION
**Pull request by pivnicek**
fixes #2

### CODE REVIEW

**Comment by odinuv** [comment]
yeah,  why not - **if** you release it separately form the pandoc thing - make a new entry in the UI

**Comment by pivnicek** [comment]
> if you release it separately form the pandoc thing

this *is* the pandoc thing :-)

**Comment by odinuv** [comment]
ok, well you haven't used it here https://github.com/keboola/docker-custom-r/pull/3 (yet)

**Comment by pivnicek** [comment]
ah, I see.  yes, I'll release this and update that PR to reference this new release.

and I'll add a new entry in the UI too, thanks for that reminder.

**Pull request merged**
